---
- name: upgrade packages.
  become: true
  apt:
    upgrade: "yes"

- name: install dependencies.
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: install pm2
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: extract artifact
  become: yes
  unarchive:
    src: artifact.tar.gz
    dest: .

- name: start app
  become: yes
  shell: |
    npm install
    pm2 stop default
    pm2 start npm --name 'UdapeopleApp' -- start



# VS Code Extension Version: 1.5.1

# ALEX
# - name: "unarchive backend files"
#   unarchive:
#     src: api.tar.gz
#     dest: /home/ubuntu/

# - name: "executing node"
#   shell: |
#     cd /home/ubuntu/backend/dist
#     pm2 stop default
#     pm2 start npm --name 'udapeople' -- start
#     pm2 ls


# OTHER
# ---
# - name: 'update packages.'
#   become: yes
#   apt:
#     upgrade: yes
#     update_cache: yes
#     cache_valid_time: 86400
# - name: remove unneeded deps
#   become: yes
#   apt:
#     autoremove: yes
# - name: install deps
#   become: yes
#   apt:
#     name: ['nodejs', 'npm']
#     state: latest
#     update_cache: yes
# - name: install pm2
#   become: yes
#   npm:
#     name: pm2
#     global: yes
#     state: latest
#     production: yes


