---
- name: upgrade packages.
  become: true
  apt:
    upgrade: "yes"

- name: install dependencies.
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: install pm2
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: extract artifact
  become: yes
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: .

- name: start app
  become: yes
  shell: |
    npm install
    pm2 stop default
    pm2 start npm --name 'UdapeopleApp' -- start



# VS Code Extension Version: 1.5.1